### ISSUE TITLE
Slug is empty when source field does not contain latin characters

### ISSUE THREAD

**Issue by newbamboo** [ismasan/sluggable-finder#2]
When the source field doesn't have latin characters, the slug comes out empty. Example: "موسيقي الزمن الجميل"

Options:
-  Transliterate characters across alphabets. That would be a lot of work, as there are many alphabets out there.
-  Use some other convention, such as "modelname-1" when the slug comes out empty.
-  Offer some kind of pluggable alternative, for developers to decide.

**Comment by ismasan** [comment]
The pluggable alternative is there: just provide a custom method as the source of the slug.

sluggable_finder :normalized_title

def normalized_title
  # check and normalize the title, etc
end
