### ISSUE TITLE
undefined method `returning' for SluggableFinder:Module (NoMethodError)

### ISSUE THREAD

**Issue by paulbjensen** [ismasan/sluggable-finder#3]
Using sluggable_finder inside a Rails 3 app, no models had been setup with sluggable_finder at this point.

StackTrace:

0   /Library/Ruby/Gems/1.8/gems/sluggable_finder-2.2.2/lib/sluggable_finder.rb  22  in `enable_activerecord'
1   /Library/Ruby/Gems/1.8/gems/sluggable_finder-2.2.2/lib/sluggable_finder.rb  60  
2   /Library/Ruby/Gems/1.8/gems/bundler-1.0.0.rc.5/lib/bundler/runtime.rb   64  in`require'
3   /Library/Ruby/Gems/1.8/gems/bundler-1.0.0.rc.5/lib/bundler/runtime.rb   64  in `require'
4   /Library/Ruby/Gems/1.8/gems/bundler-1.0.0.rc.5/lib/bundler/runtime.rb   62  in`each'
5   /Library/Ruby/Gems/1.8/gems/bundler-1.0.0.rc.5/lib/bundler/runtime.rb   62  in `require'
6   /Library/Ruby/Gems/1.8/gems/bundler-1.0.0.rc.5/lib/bundler/runtime.rb   51  in`each'
7   /Library/Ruby/Gems/1.8/gems/bundler-1.0.0.rc.5/lib/bundler/runtime.rb   51  in `require'
8   /Library/Ruby/Gems/1.8/gems/bundler-1.0.0.rc.5/lib/bundler.rb   107 in`require'
9   /Users/paulbjensen/Sites/shogunapp/config/application.rb    7  
10  /Library/Ruby/Site/1.8/rubygems/custom_require.rb   31  in `gem_original_require'
11  /Library/Ruby/Site/1.8/rubygems/custom_require.rb   31  in`require'
12  /Users/paulbjensen/Sites/shogunapp/config/environment.rb    2  
13  /Library/Ruby/Site/1.8/rubygems/custom_require.rb   31  in `gem_original_require'
14  /Library/Ruby/Site/1.8/rubygems/custom_require.rb   31  in`require'
15  config.ru   3  
16  /Library/Ruby/Gems/1.8/gems/rack-1.2.1/lib/rack/builder.rb  46  in `instance_eval'
17  /Library/Ruby/Gems/1.8/gems/rack-1.2.1/lib/rack/builder.rb  46  in`initialize'
18  config.ru   1   in `new'
19  config.ru   1

**Comment by ismasan** [comment]
I should add a disclaimer to the repo: the current version of SluggableFinder doesn't work AT ALL with Rails 3.

I plan to rewrite it from scratch for Rails 3 but don't hold your breath :(

**Comment by JakubOboza** [comment]
You should change returning to Object#tap and it will be ok.

returning was removed from rails kernel extensions

**Comment by ismasan** [comment]
Well this gem only works on Rails 2 anyway, so just using tap won't fix the root problem.
